# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'QIMA_Release.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QTextBrowser, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(828, 687)
        self.textBrowser = QTextBrowser(Form)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(25, 40, 781, 261))
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 20, 721, 16))
        self.results = QTextBrowser(Form)
        self.results.setObjectName(u"results")
        self.results.setGeometry(QRect(20, 420, 791, 261))
        self.layoutWidget = QWidget(Form)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(40, 320, 711, 26))
        self.horizontalLayout_2 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.pushButton = QPushButton(self.layoutWidget)
        self.pushButton.setObjectName(u"pushButton")

        self.horizontalLayout_2.addWidget(self.pushButton)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.filePath = QLineEdit(self.layoutWidget)
        self.filePath.setObjectName(u"filePath")

        self.horizontalLayout.addWidget(self.filePath)


        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.layoutWidget1 = QWidget(Form)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(240, 370, 291, 28))
        self.horizontalLayout_4 = QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.pushButton_2 = QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.horizontalLayout_4.addWidget(self.pushButton_2)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.pushButton_3 = QPushButton(self.layoutWidget1)
        self.pushButton_3.setObjectName(u"pushButton_3")

        self.horizontalLayout_3.addWidget(self.pushButton_3)


        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)


        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.textBrowser.setHtml(QCoreApplication.translate("Form", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#282a36;\"><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">category_dict </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','"
                        "Courier New','monospace'; font-size:14px; color:#ff79c6;\">=</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\"> {</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#282a36;\"><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">\u00a0 \u00a0 </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Co"
                        "nsolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">Commons</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">: [</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">commons</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Mo"
                        "naco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#282a36;\"><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">\u00a0 \u00a0 </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code"
                        " Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">Back End</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">: [</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">psi-se"
                        "rvice</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">wqs-service</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','"
                        "Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">aims-service</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Mo"
                        "naco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">external-service</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span"
                        "><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">data-service</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas',"
                        "'Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">document-service</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco',"
                        "'Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">irp-service</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">reports-service</sp"
                        "an><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">customer-service</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Cons"
                        "olas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">final-report-service</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro'"
                        ",'Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">file-service</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span"
                        "><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">iptb-service</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#28"
                        "2a36;\"><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">\u00a0 \u00a0 </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">Front End</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Em"
                        "oji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">: [</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">aca</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Mon"
                        "aco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">parameter-web</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><spa"
                        "n style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">irp-web</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier N"
                        "ew','monospace'; font-size:14px; color:#f1fa8c;\">psi-web</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">Public-API</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier N"
                        "ew','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">back-office</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-f"
                        "amily:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">aims-web</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace';"
                        " font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">program-web</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','m"
                        "onospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">exchange-console</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Cod"
                        "e','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">backoffice-portal-web</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; f"
                        "ont-size:14px; color:#f1fa8c;\">checklist-web</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">gi-web</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata"
                        "','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">auditor-app</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code"
                        "','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">cia-new</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; "
                        "color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">B2b-service</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple "
                        "Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">iptb-web</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Cod"
                        "e Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">b2b_dt_service</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#282a36;\"><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">\u00a0 \u00a0 </span><span style=\" font-family:'Fira Code',"
                        "'Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">EKS services</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">: [</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14"
                        "px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">claim</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Col"
                        "or Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">claim-cloud</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">aca-new</span><span style=\" font-family:'Fira Code','Consolas','Sour"
                        "ce Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">parameter-service-legacy-cloud</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:1"
                        "4px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">lt-external-service-cloud</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','"
                        "monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">ai-service-cloud</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira C"
                        "ode','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">e-signature-service-cloud</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospa"
                        "ce'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">exchange-service-cloud</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','I"
                        "nconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">exchange-worker-service-cloud</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">finance-service-c"
                        "loud</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">report-service-cloud</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color "
                        "Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">ordercore-service-cloud</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','S"
                        "ource Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">file-service-cloud</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; colo"
                        "r:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">payment-service-cloud</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','"
                        "Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">mail-service-cloud</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Conso"
                        "las','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f1fa8c;\">document-generation-service-cloud</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">]</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#282a36;\"><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; font-size:14px; color:#f8f8f2;\">}</span></p>\n"
"<p style="
                        "\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#282a36;\"><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f8f8f2;\">exclude_projects </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#ff79c6;\">=</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f8f8f2;\"> [</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','M"
                        "onaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f1fa8c;\">LT-DAO</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f1fa8c;\">LT-DTO</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courie"
                        "r New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f1fa8c;\">LT-constant</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Incons"
                        "olata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f8f8f2;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#282a36;\"><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f8f8f2;\">\u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f1fa8c;\">LT-converter</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier N"
                        "ew','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f1fa8c;\">LT-model</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata'"
                        ",'monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f8f8f2;\">, </span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f1fa8c;\">LT-utility</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#e9f284;\">'</span><span style=\" font-family:'Fira Code','Consolas','Source Code Pro','Monaco','Courier New','Inconsolata','monospace','Apple Color Emoji','Consolas','Courier New','monospace'; color:#f8f8f2;\">]</span></p></body></html>", None))
        self.label.setText(QCoreApplication.translate("Form", u"This is read CSV To Excel Format tool. If you find anything that can improved, please let me know. Thx. Email: mack.ding@qima.com", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"*Import Current Release CSV File: ", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"OK", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"Cancel", None))
    # retranslateUi

